### ISSUE TITLE
Fireworks Damage Immunity

### ISSUE THREAD

**Issue by ihymyly** [CammiesCorner/Firework-Frenzy#20]
When using Multishot enchantment, the possible damage output is greatly weakened. Please allow a configurable option to disable damage immunity and knockback caused by fireworks. The former can be disabled by default.

On another note, a 1.20.x version would be greatly appreciated.

**Comment by CammiePone** [comment]
well your second prayer is answered by the existence of this branch https://github.com/CammiePone/FireworkFix/tree/1.20-dev

as for the first one, might not be a bad idea. literally a one-line fix, even though the high damage is kinda intentional (whether or not you'll end up using it with the new damage calcs, including fall off and proper splash damage calcs though... we'll see)

**Comment by ihymyly** [comment]
Yeah I noticed the damage changes. The only problem is towards the late-game with Protection, toughness and whatnot, it falls off significantly in my opinion, dealing about 1.5 hearts of damage to full Prot-Netherite. Considering fireworks are time-consuming or expensive, I thought it'd be a nice tweak as a later-game weapon.
![2024-05-08_09 01 31](https://github.com/CammiePone/FireworkFix/assets/167125686/225d0487-c16b-4784-940c-9f9a970ad5b7)
The image below shows the small experiment. A workaround could be done using mods that change the damage-reduction formula, but seems a little excessive just to make fireworks a better weapon lol.
